import { existsSync, readFileSync } from "node:fs";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { basename, dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { writeArtifacts } from "./artifacts.js";
import { loadDocument } from "./load-document.js";
import { validateDocument } from "./validate-document.js";

const templates = resolve(dirname(fileURLToPath(import.meta.url)), "../templates");
const COPILOT_START = "<!-- provenance:start -->";
const COPILOT_END = "<!-- provenance:end -->";

export function findProjectRoot(start = process.cwd()) {
  let directory = resolve(start);
  while (true) {
    if (existsSync(join(directory, ".git"))) return directory;
    const parent = dirname(directory);
    if (parent === directory) return resolve(start);
    directory = parent;
  }
}

function displayName(value) {
  const name = value.includes("/")
    ? value.slice(value.lastIndexOf("/") + 1)
    : value;
  return name
    .split(/[-_]+/u)
    .filter(Boolean)
    .map((part) => `${part[0]?.toUpperCase() ?? ""}${part.slice(1)}`)
    .join(" ");
}

function projectName(root) {
  const packageFile = join(root, "package.json");
  if (existsSync(packageFile)) {
    try {
      const packageName = JSON.parse(readFileSync(packageFile, "utf8")).name;
      if (typeof packageName === "string" && packageName) {
        return displayName(packageName);
      }
    } catch {
      // A malformed package file must not prevent setup in a non-JavaScript project.
    }
  }
  return displayName(basename(root));
}

async function template(path) {
  return readFile(join(templates, path), "utf8");
}

async function writeManagedFile(root, target, source, protectExisting = false) {
  const path = join(root, target);
  const existed = existsSync(path);
  if (existed && protectExisting) {
    const current = await readFile(path, "utf8");
    if (!current.startsWith("# Generated by Provenance.")) return "skipped";
  }
  await mkdir(dirname(path), { recursive: true });
  await writeFile(path, await template(source));
  return existed ? "updated" : "created";
}

async function updateCopilotInstructions(root) {
  const target = ".github/copilot-instructions.md";
  const path = join(root, target);
  const snippet = await template("adapters/copilot/copilot-instructions.md");
  await mkdir(dirname(path), { recursive: true });

  if (!existsSync(path)) {
    await writeFile(path, snippet);
    return "created";
  }

  const current = await readFile(path, "utf8");
  const start = current.indexOf(COPILOT_START);
  const end = current.indexOf(COPILOT_END);
  if (start === -1 || end < start) {
    await writeFile(path, `${current.trimEnd()}\n\n${snippet}`);
    return "updated";
  }

  const after = end + COPILOT_END.length;
  await writeFile(
    path,
    `${current.slice(0, start)}${snippet.trimEnd()}${current.slice(after)}`,
  );
  return "updated";
}

export async function setupProject(start = process.cwd()) {
  const root = findProjectRoot(start);
  const created = [];
  const skipped = [];
  const updated = [];
  const recordPath = join(root, ".provenance/provenance.yaml");

  await mkdir(dirname(recordPath), { recursive: true });
  if (!existsSync(recordPath)) {
    const record = `schemaVersion: "0.1"\nproject:\n  name: ${JSON.stringify(projectName(root))}\nsources: []\nrelationships: []\n`;
    await writeFile(recordPath, record);
    created.push(".provenance/provenance.yaml");
  }

  const managedFiles = [
    [
      ".provenance/skills/provenance/SKILL.md",
      "skill/provenance/SKILL.md",
    ],
    [
      ".provenance/skills/provenance/references/record-format.md",
      "skill/provenance/references/record-format.md",
    ],
    [".agents/skills/provenance/SKILL.md", "adapters/skill/SKILL.md"],
    [".claude/skills/provenance/SKILL.md", "adapters/skill/SKILL.md"],
    [".cursor/rules/provenance.mdc", "adapters/cursor/provenance.mdc"],
    [".github/workflows/provenance.yml", "workflow/provenance.yml", true],
  ];

  for (const [target, source, protectExisting] of managedFiles) {
    const result = await writeManagedFile(
      root,
      target,
      source,
      protectExisting,
    );
    if (result === "created") created.push(target);
    if (result === "updated") updated.push(target);
    if (result === "skipped") skipped.push(target);
  }

  const copilotTarget = ".github/copilot-instructions.md";
  const copilotResult = await updateCopilotInstructions(root);
  if (copilotResult === "created") created.push(copilotTarget);
  if (copilotResult === "updated") updated.push(copilotTarget);

  const document = await loadDocument(recordPath);
  const errors = validateDocument(document);
  if (errors.length) {
    throw new Error(
      `Provenance setup found an invalid record:\n${errors
        .map((error) => `- ${error}`)
        .join("\n")}`,
    );
  }
  await writeArtifacts(document, join(root, ".provenance/output"));
  updated.push(".provenance/output/");

  return { created, root, skipped, updated };
}
